version: '3'

networks:
  local:


services:
  postgres:
    image: leonzchang/dragonstack-pg:latest
    container_name: postgres
    expose:
      - 5432/tcp
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - local

  backend:
    image: leonzchang/dragonstack-api:latest
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    environment:
      PG_USER_NAME: ${POSTGRES_USER}
      PG_USER_PWD: ${POSTGRES_PASSWORD}
      PG_DB_NAME: ${POSTGRES_DB}
      PG_DB_URL: ${PGHOST}
    networks:
      - local
    depends_on:
      - postgres

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - 8888:8080
    environment:
      ADMINER_DEFAULT_SERVER: ${PGHOST}
    networks:
      - local
